config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  
  resources :books, only: [:create, :index, :show, :edit, :destroy, :update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  devise_for :users
  get 'home/about' => 'homes#about', as: 'about'
  resources :users, only: [:show, :edit, :index, :update]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    has_many :favorites, dependent: :destroy
    has_many :book_comments, dependent: :destroy
    
    validates :title, presence: true
    validates :body, presence: true, length: { maximum: 200 }
    
    def favorited_by?(user)
      favorites.exists?(user_id: user.id)
    end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :book
    validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_one_attached :profile_image
  validates :name, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }
  
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    flash[:notice] = "Welcome! You have signed up successfully."
    user_path(current_user.id)
  end
  
  def after_sign_out_path_for(resource)
    flash[:notice] = "Signed out successfully."
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  
  def create
    @bookx = Book.find(params[:book_id])
    @book_comment = BookComment.new(book_comment_params)
    @book_comment.user_id = current_user.id
    @book_comment.book_id = @bookx.id
    if @book_comment.save
      flash[:notice] = "Book Comment was successfully created."
      redirect_to request.referer
    else
      render template: "books/show"
    end
    
    
  end
  
  def destroy
    BookComment.find(params[:id]).destroy
    flash[:notice] = "Book Comment was successfully destroyed."
    redirect_to request.referer
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  
  
  def index
    @books = Book.all
    @book = Book.new
  end
  
  # 投稿データの保存
  def create
    @books = Book.all
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book.id)
    else
      render :index
    end
  end

  def show
    @book_comment = BookComment.new
    @bookx = Book.find(params[:id])
    @book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
    unless @book.user.id == current_user.id
      redirect_to '/books'
    end
  end
  
  def update
    @book = Book.find(params[:id])
    unless @book.user.id == current_user.id
      redirect_to '/books'
    end
    if @book.update(book_params)
      flash[:notice] = "Book was successfully update."
      redirect_to book_path(@book.id)
    else
      render :edit
    end 
  end
  
  def destroy
    book = Book.find(params[:id]) 
    book.destroy  
    flash[:notice] = "Book was successfully destroyed."
    redirect_to '/books'    
  end
  
  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
  
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to request.referer
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to request.referer
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    
  end
  
  def about
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :is_matching_login_user, only: [:edit, :update]
  
  
  def show
    @user = User.find(params[:id])
    @books = @user.books 
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
    @book = Book.new
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end 
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
  
  def is_matching_login_user
    user_id = params[:id].to_i
    unless user_id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li class = "error-text"><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="container mx-auto w-50 my-5">
  
    <div><h2>Editing Book</h2></div>
    <%= form_with model: @book, url: book_path(@book.id), method: :patch do |f| %>
    <div>
      <h4>Title</h4>
      <%= f.text_field :title, style: "width:100%" %>
    </div>
    <div>
      <h4>Body</h4>
      <%= f.text_area :body, style: "width:100%" %>
    </div>
    <div>
      <%= f.submit 'Update Books', class: 'btn btn-success' %>
    </div>
    <div>
      <p>
        <%= link_to "Show", book_path(@book.id) %><span>|</span><%= link_to "Back", books_path %>
      </p>
    </div>
    <% end %>
  
</div>

app/views/books/index.html.erb
<div class = "success">
  <%= flash[:notice] %>
</div>
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li class = "error-text"><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= image_tag current_user.get_profile_image(80,80) %>
      <table class="table table-striped">
        <tr></tr>
        <tr>
          <th>name</th>
          <th><%= current_user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= current_user.introduction %></th>
        </tr>
      </table>
      <%= link_to edit_user_path(current_user.id) do %>
        <button type="button" class="btn btn-outline-secondary btn-block"><i class="fas fa-user-cog"></i></button>
      <% end %>
      <h2>New book</h2>
      <%= form_with model: @book do |f| %>
      <div>
        <h4>Title</h4>
        <%= f.text_field :title %>
      </div>
      <div>
        <h4>Opinion</h4>
        <%= f.text_area :body %>
      </div>
      <div>
        <%= f.submit 'Create Book', class: 'btn btn-success' %>
      </div>
      <% end %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-striped">
        <tr>
          <th colspan = "1"></th>
          <th>Title</th>
          <th>Body</th>
          <th colspan = "2"></th>
        </tr>
        <% @books.each do |book| %>
        <tr>
          <td><%= link_to user_path(book.user.id) do %><%= image_tag book.user.get_profile_image(80,80) %><% end %></td>
          <td><%= link_to book_path(book.id) do %><%= book.title %><% end %></td>
          <td><%= book.body %></td>
          <% if book.favorited_by?(current_user) %>
            <td><%= link_to book_favorites_path(book), method: :delete do %><i class="fas fa-heart"></i><%= book.favorites.count %><% end %></td>
          <% else %>
            <td><%= link_to book_favorites_path(book), method: :post do %><i class="far fa-heart"></i><%= book.favorites.count %><% end %></td>
          <% end %>
          <td>コメント数：<%= book.book_comments.count %></td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class = "success">
  <%= flash[:notice] %>
</div>
<% if @book_comment.errors.any? %>
  <%= @book_comment.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book_comment.errors.full_messages.each do |message| %>
      <li class = "error-text"><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= image_tag @bookx.user.get_profile_image(80,80) %>
      <table class="table table-striped">
        <tr></tr>
        <tr>
          <th>name</th>
          <th><%= @bookx.user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= @bookx.user.introduction %></th>
        </tr>
      </table>
      <%= link_to edit_user_path(@bookx.user.id) do %>
        <button type="button" class="btn btn-outline-secondary btn-block"><i class="fas fa-user-cog"></i></button>
      <% end %>
      <h2>New book</h2>
      <%= form_with model: @book do |f| %>
      <div>
        <h4>Title</h4>
        <%= f.text_field :title %>
      </div>
      <div>
        <h4>Opinion</h4>
        <%= f.text_area :body %>
      </div>
      <div>
        <%= f.submit 'Create Book', class: 'btn btn-success' %>
      </div>
      <% end %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book details</h2>
      <table class="table table-striped">
        <tr>
          <th colspan = "1"></th>
          <th>Title</th>
          <th>Body</th>
          <th colspan = "2"></th>
          <% if @bookx.user == current_user %>
            <th colspan = "2"></th>
          <% end %>
        </tr>
        <tr>
          <td>
            <%= link_to user_path(@bookx.user.id) do %>
            <%= image_tag @bookx.user.get_profile_image(80,80) %>
            <p><%= @bookx.user.name %></p>
            <% end %>
          </td>
          <td><%= @bookx.title %></td>
          <td><%= @bookx.body %></td>
          <% if @bookx.favorited_by?(current_user) %>
            <td><%= link_to book_favorites_path(@bookx), method: :delete do %><i class="fas fa-heart"></i><%= @bookx.favorites.count %><% end %></td>
          <% else %>
            <td><%= link_to book_favorites_path(@bookx), method: :post do %><i class="far fa-heart"></i><%= @bookx.favorites.count %><% end %></td>
          <% end %>
          <% if @bookx.user == current_user %>
            <td><%= link_to "Edit", edit_book_path(@bookx.id), class: 'btn btn-success' %></td>
            <td><%= link_to "Destroy", book_path(@bookx), method: :delete, class: 'btn btn-danger' %></td>
          <% end %>
          <td>コメント数：<%= @bookx.book_comments.count %></td>
        </tr>
      </table>
      <% @bookx.book_comments.each do |book_comment| %>
      <div class="d-flex">
        <div class="mr-3">
          <%= link_to user_path(book_comment.user.id) do %>
            <%= image_tag book_comment.user.get_profile_image(50,50) %>
            <p><%= book_comment.user.name %></p>
          <% end %>
        </div>
        <div class="mr-3">
          <p><%= book_comment.comment %></p>
        </div>
        <div>
          <% if book_comment.user == current_user %>
            <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class: 'btn btn-danger' %>
          <% end %> 
        </div>
      </div>
      <% end %>
      <div>
        <%= form_with model: [@bookx, @book_comment] do |f| %>
          <div><%= f.text_area :comment, style: "width:75%", rows: '5', placeholder: "コメントをここに" %></div>
          <div><%= f.submit "送信" %></div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container mx-auto w-50 my-5">
    <h1 class="text-center">Welcome to <i class="fas fa-book"></i>Bookers!</h1>
</div>

app/views/homes/top.html.erb
<div class = "success">
  <%= flash[:notice] %>
</div>
<div class="container mx-auto w-50 my-5">
    
    <h1 class="d-block">welcome to <i class="fas fa-book"></i>Bookers !!</h1>

    <p class="d-block">In Bookers,</p>

    <p class="d-block">you can share and exchange your opinions , inpressions , and emotions</p>

    <p class="d-block">about various books!</p>
    <div class="row">
      <div class="col-md">
        <button type="button" class="btn btn-primary btn-block"><%= link_to "Log in", new_user_session_path, class: 'text-white' %></button>
        <button type="button" class="btn btn-success btn-block"><%= link_to "Sign up",new_user_registration_path, class: 'text-white' %></button>
      </div>
    </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-auto">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand p-3" href="/">Bookers</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to user_path(current_user.id), class: 'nav-link text-white' do %>
              <i class="fas fa-home"></i><span>Home</span>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to users_path, class: 'nav-link text-white' do %>
              <i class="fas fa-users"></i><span>Users</span>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to books_path, class: 'nav-link text-white' do %>
              <i class="fas fa-book-open"></i><span>Books</span>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-white' do %>
                <i class="fas fa-sign-out-alt"></i><span>Log out</span>
              <% end %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to root_path, class: 'nav-link text-white' do %>
                <i class="fas fa-home"></i><span>Home</span>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to about_path, class: 'nav-link text-white' do %>
                <i class="fas fa-link"></i><span>About</span>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_registration_path, class: 'nav-link text-white' do %>
              <i class="fas fa-user-plus"></i><span>Sign up</span>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_session_path, class: 'nav-link text-white' do %>
              <i class="fas fa-sign-in-alt"></i><span>Log in</span>
              <% end %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
    <%= yield %>
    </main>
    <footer class="mt-5">
      <div class="container">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li class = "error-text"><%= message %></li>
    <% end %>
  </ul>
<% end %>
<div class="container mx-auto w-50 my-5">
  
    <div class="row"><h2>User info</h2></div>
    <%= form_with model: @user, local: true, method: :patch do |f| %>
    <div class="row">
      <h4>Name</h4>
      <%= f.text_field :name, autofocus: true, placeholder:"名前", style: "width:100%"%>
    </div>
    <div class="row">
      <h4>Introduction</h4>
      <%= f.text_area :introduction, autofocus: true, style: "width:100%" %>
    </div>
    <div class="row flex-column">
      <h4>Image</h4>
      <p><%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %></p> 
    </div>
    <div class="row">
      <%= f.submit "Update User", class: 'btn btn-secondary' %>
    </div>
    <% end %>
  
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= image_tag current_user.get_profile_image(80,80) %>
      <table class="table table-striped">
        <tr></tr>
        <tr>
          <th>name</th>
          <th><%= current_user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= current_user.introduction %></th>
        </tr>
      </table>
      <%= link_to edit_user_path(current_user.id) do %>
        <button type="button" class="btn btn-outline-secondary btn-block"><i class="fas fa-user-cog"></i></button>
      <% end %>
      <h2>New book</h2>
      <%= form_with model: @book do |f| %>
      <div>
        <h4>Title</h4>
        <%= f.text_field :title %>
      </div>
      <div>
        <h4>Opinion</h4>
        <%= f.text_area :body %>
      </div>
      <div>
        <%= f.submit 'Create Book', class: 'btn btn-success' %>
      </div>
      <% end %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table table-striped">
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan = "1"></th>
        </tr>
        <% @users.each do |user| %>
        <tr>
          <td><%= image_tag user.get_profile_image(80,80) %></td>
          <td><%= user.name %></td>
          <td><%= link_to "Show", user_path(user.id) %></td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class = "success">
  <%= flash[:notice] %>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= image_tag @user.get_profile_image(80,80) %>
      <table class="table table-striped">
        <tr></tr>
        <tr>
          <th>name</th>
          <th><%= @user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= @user.introduction %></th>
        </tr>
      </table>
      <%= link_to edit_user_path(@user.id) do %>
        <button type="button" class="btn btn-outline-secondary btn-block"><i class="fas fa-user-cog"></i></button>
      <% end %>
      <h2>New book</h2>
      <%= form_with model: @book do |f| %>
      <div>
        <h4>Title</h4>
        <%= f.text_field :title %>
      </div>
      <div>
        <h4>Opinion</h4>
        <%= f.text_area :body %>
      </div>
      <div>
        <%= f.submit 'Create Book', class: 'btn btn-success' %>
      </div>
      <% end %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-striped">
        <tr>
          <th colspan = "1"></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan = "2"></th>
        </tr>
        <% @books.each do |book| %>
        <tr>
          <td><%= link_to user_path(book.user.id) do %><%= image_tag book.user.get_profile_image(80,80) %><% end %></td>
          <td><%= link_to book_path(book.id) do %><%= book.title %><% end %></td>
          <td><%= book.body %></td>
          <% if book.favorited_by?(current_user) %>
            <td><%= link_to book_favorites_path(book), method: :delete do %><i class="fas fa-heart"></i><%= book.favorites.count %><% end %></td>
          <% else %>
            <td><%= link_to book_favorites_path(book), method: :post do %><i class="far fa-heart"></i><%= book.favorites.count %><% end %></td>
          <% end %>
          <td>コメント数：<%= book.book_comments.count %></td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>